name: $(BuildID)

trigger:
  branches:
    include: # we build for all branches. selection happens in stages
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: ubuntu-latest

stages:
  - template: ./azure-pipelines/publish-package.yml
    parameters:
      stage: prod
      branch: master

  - template: ./azure-pipelines/publish-package.yml
    parameters:
      stage: dev
      branch: develop
